#include <ctype.h>
#include "dblayer.h"
#include <limits.h>
#include <netinet/in.h>
#include "server.h"
#include "settings.h"
#include <signal.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>